version: '3'

services:

  neo4j:
    build: ./neo4j
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_dbms_shell_enabled=true

  elasticsearch:
    build: ./elasticsearch
    ports:
      - 9200:9200

  kibana:
    build: ./kibana
    ports:
      - 5601:5601
    volumes:
      - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    links:
      - elasticsearch

  api:
    build: ./api
    ports:
      - 4001:4001
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=letmein
      - GRAPHQL_LISTEN_PORT=4001
      - GRAPHQL_URI=http://api:4001/graphql
      - ELASTIC_URI=http://elasticsearch:9200
      - DEBUG=neo4j-graphql-js
    volumes:
    - ./api/src:/app/src
    links:
    - neo4j
    - elasticsearch
    depends_on:
    - neo4j
    - elasticsearch

  federation:
    build: ./federation
    ports:
      - 4000:4000

  ui:
    build: ./ui-react
    ports:
      - 3000:3000
    environment:
      - REACT_APP_GRAPHQL_URI=/graphql
      - PROXY=http://api:4001/graphql
    links:
    - api
    depends_on:
    - api

  ui-angular:
    build: ./ui-react
    ports:
      - 3000:3000
    environment:
      - REACT_APP_GRAPHQL_URI=/graphql
      - PROXY=http://api:4001/graphql
    links:
    - api
    depends_on:
    - api
